### ISSUE TITLE
iox-roudi C++ sdk

### ISSUE THREAD

**Issue by YeahhhhLi** [eclipse-iceoryx/iceoryx-rs#67]
## Brief feature description

Our service uses iox-roudi when communicating with cyclonedds shm.

Since cyclonedds depends on the iox-roudi service, we have to start the iox-roudi service before running our own C++ service.

Is there any sdk way to integrate iox-roudi in our C++ system?

**Comment by elBoberido** [comment]
@YeahhhhLi I think this would fit better to https://github.com/eclipse-iceoryx/iceoryx which is used by cyclonedds. But I can also answer your question. Currently there is unfortunately no way and you have to start iox-roudi manually.

There is this issue https://github.com/eclipse-iceoryx/iceoryx/issues/970. Most probably it will result in a CLI application and you can run your applications like `iox run your-app-name`. This would ensure that there is a running iox-roudi application before starting your application.

**Comment by YeahhhhLi** [comment]
> I think this would fit better to https://github.com/eclipse-iceoryx/iceoryx which is used by cyclonedds. 
The issue was indeed sent to the wrong place. I was a little interested in the rust version, but the issue was posted here by mistake.

> Currently there is unfortunately no way and you have to start iox-roudi manually.
OK, thanks~
